export { default as BaseButton } from './BaseButton.vue'
export { default as TextButton } from './TextButton.vue'
export { default as TheHeader } from './TheHeader.vue'
export { default as TheBasket } from './TheBasket.vue'
export { default as BasketProducts } from './BasketProducts.vue'
export { default as BasketSummary } from './BasketSummary.vue'
